export const AUTH_USER = 'auth_user'
export const UNAUTH_USER = 'unauth_user'
export const AUTH_ERROR = 'auth_error'
export const FETCH_PROMOS = 'fetch_promos'
export const FETCH_MERCHANT_INFO = 'fetch_merchant_info'
export const EDIT_PROMO = 'edit_promo'
export const CREATE_PROMO = 'create_promo'
